---
- include_tasks: is_systemd.yml

# Variable configuration.
- include_tasks: variables.yml

- name: Ensure old versions of Docker are not installed.
  apt:
    name:
      - docker
      - docker-engine
      - docker.io
      - containerd
      - runc
    state: absent

- name: Ensure dependencies are installed.
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - debian-keyring
      - debian-archive-keyring
      - apt-transport-https
      - gnupg2
      - curl
    state: present

- name: Add Docker apt key.
  become: true
  become_user: root
  apt_key:
    url: "{{ docker_apt_gpg_key }}"
    state: present

- name: Add Docker repository.
  apt_repository:
    repo: "{{ docker_apt_repository }}"
    state: present
    update_cache: true

- name: Install Docker.
  apt:
    name: "{{ docker_packages }}"
    state: present

- name: Install Docker Compose SDK for python.
  become: true
  become_user: root
  pip:
    name:
      - docker
      - docker-compose
    state: present
    executable: pip3
  notify: restart docker

- name: Ensure Docker is started and enabled at boot.
  systemd:
    name: docker
    state: "{{ docker_service_state }}"
    enabled: "{{ docker_service_enabled }}"
  when: systemd_pid_1 is defined and systemd_pid_1

- name: Ensure handlers are notified now to avoid firewall conflicts.
  meta: flush_handlers

- include_tasks: docker-compose.yml
  when: docker_install_compose | bool


- include_tasks: docker-users.yml
  when: docker_users | length > 0
